//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using NHibernate.Mapping;
using SQLitePCL;
using System;
using System.Diagnostics.CodeAnalysis;

namespace BeSpokedBikes
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SqliteConnection db = new SqliteConnection(_path))
            {
                db.CreateTable<__EFMigrationsHistory>();
                db.CreateTable<Customers>();
                db.CreateTable<Discount>();
                db.CreateTable<Products>();
                db.CreateTable<Sales>();
                db.CreateTable<Salespeople>();
            }
        }
    }
    public partial class __EFMigrationsHistory
    {
       
        public String MigrationId { get; set; }
        
        [NotNull]
        public String ProductVersion { get; set; }
        
    }
    
    public partial class Customers
    {
      
        public Int64 CustomerId { get; set; }
        
        [NotNull]
        public String FirstName { get; set; }
        
        [NotNull]
        public String LastName { get; set; }
        
        [NotNull]
        public String Address { get; set; }
        
        [NotNull]
        public String PhoneNumber { get; set; }
        
        [NotNull]
        public String StartDate { get; set; }
        
    }
    
    public partial class Discount
    {
       
        public Int64 DiscountId { get; set; }
        
        [NotNull]
        public Int64 ProductId { get; set; }
        
        [NotNull]
        public String StartDate { get; set; }
        
        [NotNull]
        public String EndDate { get; set; }
        
        [NotNull]
        public String DiscountPercentage { get; set; }
        
    }
    
    public partial class Products
    {
     
        public Int64 ProductId { get; set; }
        
        [NotNull]
        public String Name { get; set; }
        
        [NotNull]
        public String Manufacturer { get; set; }
        
        public String Style { get; set; }
        
        [NotNull]
        public Int64 PurchasePrice { get; set; }
        
        [NotNull]
        public Int64 SalePrice { get; set; }
        
        [NotNull]
        public Int64 Quantity { get; set; }
        
        [NotNull]
        public Double CommissionPercentage { get; set; }
        
        [NotNull]
        public Int64 DiscountId { get; set; }
        
    }
    
    public partial class Sales
    {
       
        public Int64 SaleId { get; set; }
        
     
        [NotNull]
        public Int64 ProductId { get; set; }
        
       
        [NotNull]
        public Int64 SalespersonId { get; set; }
        
        
        [NotNull]
        public Int64 CustomerId { get; set; }
        
        [NotNull]
        public String SalesDate { get; set; }
        
    }
    
    public partial class Salespeople
    {
       
        public Int64 SalespersonId { get; set; }
        
        [NotNull]
        public String FirstName { get; set; }
        
        [NotNull]
        public String LastName { get; set; }
        
        public String Address { get; set; }
        
        public String PhoneNumber { get; set; }
        
        [NotNull]
        public String StartDate { get; set; }
        
        [NotNull]
        public String TerminationDate { get; set; }
        
        public String Manager { get; set; }
        
    }
    
}
